apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  namespace: cert-manager
  name: selfsigned-cluster-issuer
spec: 
  selfSigned: {}

---

apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: ca-certificate 
  namespace: default
spec:
  isCA: true
  commonName: ca.default
  secretName: ca-key-pair
  issuerRef:
    name: selfsigned-cluster-issuer
    kind: ClusterIssuer