apiVersion: cert-manager.io/v1 
kind: Certificate
metadata:
  namespace: default
  name: enclave-cert
spec:
  secretName: enclave-tls
  commonName: enclave.default.svc
  dnsNames:
    - enclave.default.svc
  duration: 24h
  renewBefore: 12h
  issuerRef:
    name: selfsigned-cluster-issuer
    kind: ClusterIssuer
  usages:
  - digital signature
  - key encipherment
  - server auth  
  - client auth 