apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  namespace: default
  name: licensing-server-cert
spec:
  secretName: licensing-server-tls
  duration: 2160h  # expires in 90 days
  renewBefore: 360h # 10 days before expiry
  issuerRef:
    name: selfsigned-cluster-issuer
    kind: ClusterIssuer
  commonName: licensing-server-svc.default.svc
  dnsNames:
    - licensing-server-svc.default.svc
  usages:
    - digital signature
    - key encipherment
    - server auth  
    - client auth  

