apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: enclave-creator
  namespace: default 
rules:
  - apiGroups: [""]
    resources: ["pods"]
    verbs: ["create", "get", "list", "watch"]
