apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: licensing-server-role-binding
  namespace: default  
subjects:
  - kind: ServiceAccount
    name: licensing-server-sa
    namespace: default  
roleRef:
  kind: Role
  name: enclave-creator
  apiGroup: rbac.authorization.k8s.io
